//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szoftech2_U945X9_Beadandó
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizetésiMód
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FizetésiMód()
        {
            this.Rendelés = new HashSet<Rendelés>();
        }
    
        public byte FizetésimódSK { get; set; }
        public string Mód { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendelés> Rendelés { get; set; }
    }
}
