//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szoftech2_U945X9_Beadandó
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Butor_rendelesEntities6 : DbContext
    {
        public Butor_rendelesEntities6()
            : base("name=Butor_rendelesEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FizetésiMód> FizetésiMód { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Márka> Márka { get; set; }
        public virtual DbSet<Rendelés> Rendelés { get; set; }
        public virtual DbSet<Rendelt_Termék> Rendelt_Termék { get; set; }
        public virtual DbSet<Termék> Termék { get; set; }
        public virtual DbSet<Vásárló> Vásárló { get; set; }
    }
}
