//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szoftech2_U945X9_Beadandó
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendelt_Termék
    {
        public Nullable<byte> RendelésFK { get; set; }
        public Nullable<byte> TermékFK { get; set; }
        public Nullable<int> Mennyiség { get; set; }
        public byte RendelelésazonosítóSK { get; set; }
    
        public virtual Rendelés Rendelés { get; set; }
        public virtual Termék Termék { get; set; }
    }
}
