//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szoftech2_U945X9_Beadandó
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termék
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termék()
        {
            this.Rendelt_Termék = new HashSet<Rendelt_Termék>();
        }
    
        public byte TermékSK { get; set; }
        public string TermékNév { get; set; }
        public Nullable<byte> KategoriaFK { get; set; }
        public Nullable<byte> MárkaFK { get; set; }
        public Nullable<int> Ár { get; set; }
        public Nullable<byte> Elemszám { get; set; }
        public Nullable<int> Súly { get; set; }
        public Nullable<int> Méret { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Márka Márka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendelt_Termék> Rendelt_Termék { get; set; }
    }
}
